//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Customer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public int id { get; set; }
        public string name { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public int cid { get; set; }
        public string country { get; set; }
        public Nullable<int> postcode { get; set; }
        public string email { get; set; }
        public Nullable<int> mobile { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<System.DateTime> updateddate { get; set; }
    
        public virtual City City { get; set; }
    }
}
